/**
 * claude-prism — HANDOFF.md Generation
 * Shared logic for auto-generating session handoff documents
 */

import { readFileSync, existsSync, readdirSync } from 'fs';
import { join } from 'path';
import { execSync } from 'child_process';

/**
 * Generate HANDOFF.md content from current project state
 * @param {string} projectRoot - Project root directory
 * @returns {string} Markdown content for HANDOFF.md
 */
export function generateHandoff(projectRoot) {
  const sections = [];
  sections.push('# HANDOFF — Session Transition Document\n');
  sections.push(`> Auto-generated by claude-prism at ${new Date().toISOString()}\n`);

  // 1. Plan progress
  const planInfo = getActivePlanInfo(projectRoot);
  sections.push('## Status\n');
  if (planInfo) {
    const { total, done, planName } = planInfo;
    const pct = total > 0 ? Math.round((done / total) * 100) : 0;
    sections.push(`- Active plan: \`${planName}\``);
    sections.push(`- Progress: ${done}/${total} tasks (${pct}%)`);
    if (planInfo.nextBatch) {
      sections.push(`- Next batch: ${planInfo.nextBatch}`);
    }
  } else {
    sections.push('- No active plan file found');
  }

  // 2. Current git state
  sections.push('\n## Current State\n');
  const gitInfo = getGitInfo(projectRoot);
  sections.push(`- Branch: \`${gitInfo.branch}\``);
  if (gitInfo.uncommitted > 0) {
    sections.push(`- Uncommitted changes: ${gitInfo.uncommitted} file(s)`);
  } else {
    sections.push('- Working tree clean');
  }
  if (gitInfo.recentCommits.length > 0) {
    sections.push('\nRecent commits:');
    for (const commit of gitInfo.recentCommits) {
      sections.push(`- ${commit}`);
    }
  }

  // 3. Next steps (derived from plan)
  sections.push('\n## Next Steps\n');
  if (planInfo && planInfo.nextTasks.length > 0) {
    for (const task of planInfo.nextTasks) {
      sections.push(`- [ ] ${task}`);
    }
  } else {
    sections.push('- Review current state and determine next action');
  }

  // 4. Decisions placeholder
  sections.push('\n## Decisions Made\n');
  sections.push('- (Populated by session context — review plan file for architectural decisions)');

  // 5. Known issues
  sections.push('\n## Known Issues\n');
  sections.push('- (None auto-detected — review test results and build output)');

  return sections.join('\n') + '\n';
}

/**
 * Parse YAML-like frontmatter from markdown content
 * @param {string} content - Markdown file content
 * @returns {Object} Parsed frontmatter key-value pairs
 */
export function parseFrontmatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---/);
  if (!match) return {};
  const fm = {};
  for (const line of match[1].split('\n')) {
    const [key, ...rest] = line.split(':');
    if (key && rest.length) {
      const val = rest.join(':').trim();
      if (val.startsWith('[')) {
        try { fm[key.trim()] = JSON.parse(val); } catch { fm[key.trim()] = val; }
      } else {
        fm[key.trim()] = val;
      }
    }
  }
  return fm;
}

/**
 * Get all plans with frontmatter and progress info
 * @param {string} projectRoot - Project root directory
 * @returns {Array<Object>} Array of plan objects
 */
export function getAllPlans(projectRoot) {
  const plansDir = join(projectRoot, '.prism', 'plans');
  if (!existsSync(plansDir)) return [];
  const files = readdirSync(plansDir).filter(f => f.endsWith('.md')).sort().reverse();
  return files.map(f => {
    const content = readFileSync(join(plansDir, f), 'utf8');
    const fm = parseFrontmatter(content);
    const parsed = parsePlanContent(content, f);
    return { file: f, content, ...fm, ...parsed };
  });
}

/**
 * Read active plan file and extract progress info
 * Now uses frontmatter status to find active plans
 */
export function getActivePlanInfo(projectRoot) {
  const plans = getAllPlans(projectRoot);
  if (plans.length === 0) return null;

  // Find the most recent plan with status: active (or no frontmatter = default active)
  const activePlan = plans.find(p => (p.status || 'active') === 'active');
  if (!activePlan) return null;

  return parsePlanContent(
    readFileSync(join(projectRoot, '.prism', 'plans', activePlan.file), 'utf8'),
    activePlan.file
  );
}

/**
 * Parse plan markdown content for progress info
 * @param {string} content - Plan file content
 * @param {string} planName - Plan filename
 * @returns {{ planName, total, done, nextBatch, nextTasks, currentBatchFiles }}
 */
export function parsePlanContent(content, planName) {
  const lines = content.split('\n');
  let total = 0;
  let done = 0;
  let nextBatch = null;
  const nextTasks = [];
  let currentBatchFiles = [];
  let inUnfinishedBatch = false;
  let currentBatchName = '';

  for (const line of lines) {
    const checkboxMatch = line.match(/^[-*]\s+\[([ x])\]\s+(.+)/);
    if (checkboxMatch) {
      total++;
      if (checkboxMatch[1] === 'x') {
        done++;
      } else {
        if (!inUnfinishedBatch) {
          // First unfinished task — we're in the current batch
          inUnfinishedBatch = true;
        }
        if (nextTasks.length < 5) {
          nextTasks.push(checkboxMatch[2]);
        }
      }
    }

    // Detect batch headers
    const batchMatch = line.match(/^#{1,3}\s+Batch\s+\d+[:\s]*(.+)?/i);
    if (batchMatch) {
      if (!nextBatch && inUnfinishedBatch) {
        // Already past it
      } else if (!nextBatch) {
        // Check if there are unchecked items below
      }
      currentBatchName = batchMatch[0];
    }

    // Track file references in current batch
    if (inUnfinishedBatch) {
      const fileMatch = line.match(/`([^`]+\.\w+)`/);
      if (fileMatch && fileMatch[1].includes('/')) {
        currentBatchFiles.push(fileMatch[1]);
      }
    }
  }

  // Find the first batch with uncompleted items
  let batchDone = 0;
  let batchTotal = 0;
  let foundFirstUncompleted = false;
  for (const line of lines) {
    const batchMatch = line.match(/^#{1,3}\s+(Batch\s+\d+[:\s]*.+)/i);
    if (batchMatch) {
      if (batchTotal > 0 && batchDone < batchTotal && !foundFirstUncompleted) {
        nextBatch = currentBatchName;
        foundFirstUncompleted = true;
      }
      currentBatchName = batchMatch[1];
      batchDone = 0;
      batchTotal = 0;
    }
    const cb = line.match(/^[-*]\s+\[([ x])\]/);
    if (cb) {
      batchTotal++;
      if (cb[1] === 'x') batchDone++;
    }
  }
  if (!foundFirstUncompleted && batchTotal > 0 && batchDone < batchTotal) {
    nextBatch = currentBatchName;
  }

  return { planName, total, done, nextBatch, nextTasks, currentBatchFiles };
}

/**
 * Detect file overlaps across active plans
 * @param {string} projectRoot - Project root directory
 * @returns {Array<{file: string, plans: string[]}>} Conflicting files
 */
export function detectPlanConflicts(projectRoot) {
  const plans = getAllPlans(projectRoot).filter(p => (p.status || 'active') === 'active');
  const fileMap = new Map();

  for (const plan of plans) {
    const files = extractFilesInScope(plan.content || '');
    for (const f of files) {
      if (!fileMap.has(f)) fileMap.set(f, []);
      fileMap.get(f).push(plan.file);
    }
  }

  const conflicts = [];
  for (const [file, planList] of fileMap) {
    if (planList.length > 1) {
      conflicts.push({ file, plans: planList });
    }
  }
  return conflicts;
}

/**
 * Extract file paths from "Files in Scope" section
 * @param {string} content - Plan markdown content
 * @returns {string[]} File paths found
 */
function extractFilesInScope(content) {
  const scopeMatch = content.match(/##\s+Files\s+in\s+Scope\s*\n([\s\S]*?)(?=\n##|\n---|\s*$)/i);
  if (!scopeMatch) return [];
  const paths = [];
  const backtickRegex = /`([^`]+\.[a-z]+)`/g;
  let m;
  while ((m = backtickRegex.exec(scopeMatch[1])) !== null) {
    paths.push(m[1]);
  }
  return paths;
}

/**
 * Get git status info
 */
function getGitInfo(projectRoot) {
  const info = { branch: 'unknown', uncommitted: 0, recentCommits: [] };

  try {
    info.branch = execSync('git rev-parse --abbrev-ref HEAD', {
      cwd: projectRoot, encoding: 'utf8', timeout: 5000
    }).trim();
  } catch { /* not a git repo */ }

  try {
    const status = execSync('git status --porcelain', {
      cwd: projectRoot, encoding: 'utf8', timeout: 5000
    }).trim();
    if (status) {
      info.uncommitted = status.split('\n').filter(Boolean).length;
    }
  } catch { /* ignore */ }

  try {
    const log = execSync('git log --oneline -3', {
      cwd: projectRoot, encoding: 'utf8', timeout: 5000
    }).trim();
    if (log) {
      info.recentCommits = log.split('\n');
    }
  } catch { /* ignore */ }

  return info;
}
