/**
 * claude-prism — HANDOFF.md Generation
 * Shared logic for auto-generating session handoff documents
 */

import { readFileSync, existsSync, readdirSync } from 'fs';
import { join } from 'path';
import { execSync } from 'child_process';

/**
 * Generate HANDOFF.md content from current project state
 * @param {string} projectRoot - Project root directory
 * @returns {string} Markdown content for HANDOFF.md
 */
export function generateHandoff(projectRoot) {
  const sections = [];
  sections.push('# HANDOFF — Session Transition Document\n');
  sections.push(`> Auto-generated by claude-prism at ${new Date().toISOString()}\n`);

  // 1. Plan progress
  const planInfo = getActivePlanInfo(projectRoot);
  sections.push('## Status\n');
  if (planInfo) {
    const { total, done, planName } = planInfo;
    const pct = total > 0 ? Math.round((done / total) * 100) : 0;
    sections.push(`- Active plan: \`${planName}\``);
    sections.push(`- Progress: ${done}/${total} tasks (${pct}%)`);
    if (planInfo.nextBatch) {
      sections.push(`- Next batch: ${planInfo.nextBatch}`);
    }
  } else {
    sections.push('- No active plan file found');
  }

  // 2. Current git state
  sections.push('\n## Current State\n');
  const gitInfo = getGitInfo(projectRoot);
  sections.push(`- Branch: \`${gitInfo.branch}\``);
  if (gitInfo.uncommitted > 0) {
    sections.push(`- Uncommitted changes: ${gitInfo.uncommitted} file(s)`);
  } else {
    sections.push('- Working tree clean');
  }
  if (gitInfo.recentCommits.length > 0) {
    sections.push('\nRecent commits:');
    for (const commit of gitInfo.recentCommits) {
      sections.push(`- ${commit}`);
    }
  }

  // 3. Next steps (derived from plan)
  sections.push('\n## Next Steps\n');
  if (planInfo && planInfo.nextTasks.length > 0) {
    for (const task of planInfo.nextTasks) {
      sections.push(`- [ ] ${task}`);
    }
  } else {
    sections.push('- Review current state and determine next action');
  }

  // 4. Decisions placeholder
  sections.push('\n## Decisions Made\n');
  sections.push('- (Populated by session context — review plan file for architectural decisions)');

  // 5. Known issues
  sections.push('\n## Known Issues\n');
  sections.push('- (None auto-detected — review test results and build output)');

  return sections.join('\n') + '\n';
}

/**
 * Read active plan file and extract progress info
 */
export function getActivePlanInfo(projectRoot) {
  const plansDir = join(projectRoot, '.prism', 'plans');
  if (!existsSync(plansDir)) return null;

  const planFiles = readdirSync(plansDir)
    .filter(f => f.endsWith('.md'))
    .sort()
    .reverse();

  if (planFiles.length === 0) return null;

  const planName = planFiles[0];
  const content = readFileSync(join(plansDir, planName), 'utf8');

  return parsePlanContent(content, planName);
}

/**
 * Parse plan markdown content for progress info
 * @param {string} content - Plan file content
 * @param {string} planName - Plan filename
 * @returns {{ planName, total, done, nextBatch, nextTasks, currentBatchFiles }}
 */
export function parsePlanContent(content, planName) {
  const lines = content.split('\n');
  let total = 0;
  let done = 0;
  let nextBatch = null;
  const nextTasks = [];
  let currentBatchFiles = [];
  let inUnfinishedBatch = false;
  let currentBatchName = '';

  for (const line of lines) {
    const checkboxMatch = line.match(/^[-*]\s+\[([ x])\]\s+(.+)/);
    if (checkboxMatch) {
      total++;
      if (checkboxMatch[1] === 'x') {
        done++;
      } else {
        if (!inUnfinishedBatch) {
          // First unfinished task — we're in the current batch
          inUnfinishedBatch = true;
        }
        if (nextTasks.length < 5) {
          nextTasks.push(checkboxMatch[2]);
        }
      }
    }

    // Detect batch headers
    const batchMatch = line.match(/^#{1,3}\s+Batch\s+\d+[:\s]*(.+)?/i);
    if (batchMatch) {
      if (!nextBatch && inUnfinishedBatch) {
        // Already past it
      } else if (!nextBatch) {
        // Check if there are unchecked items below
      }
      currentBatchName = batchMatch[0];
    }

    // Track file references in current batch
    if (inUnfinishedBatch) {
      const fileMatch = line.match(/`([^`]+\.\w+)`/);
      if (fileMatch && fileMatch[1].includes('/')) {
        currentBatchFiles.push(fileMatch[1]);
      }
    }
  }

  // Find the first batch with uncompleted items
  let batchDone = 0;
  let batchTotal = 0;
  let foundFirstUncompleted = false;
  for (const line of lines) {
    const batchMatch = line.match(/^#{1,3}\s+(Batch\s+\d+[:\s]*.+)/i);
    if (batchMatch) {
      if (batchTotal > 0 && batchDone < batchTotal && !foundFirstUncompleted) {
        nextBatch = currentBatchName;
        foundFirstUncompleted = true;
      }
      currentBatchName = batchMatch[1];
      batchDone = 0;
      batchTotal = 0;
    }
    const cb = line.match(/^[-*]\s+\[([ x])\]/);
    if (cb) {
      batchTotal++;
      if (cb[1] === 'x') batchDone++;
    }
  }
  if (!foundFirstUncompleted && batchTotal > 0 && batchDone < batchTotal) {
    nextBatch = currentBatchName;
  }

  return { planName, total, done, nextBatch, nextTasks, currentBatchFiles };
}

/**
 * Get git status info
 */
function getGitInfo(projectRoot) {
  const info = { branch: 'unknown', uncommitted: 0, recentCommits: [] };

  try {
    info.branch = execSync('git rev-parse --abbrev-ref HEAD', {
      cwd: projectRoot, encoding: 'utf8', timeout: 5000
    }).trim();
  } catch { /* not a git repo */ }

  try {
    const status = execSync('git status --porcelain', {
      cwd: projectRoot, encoding: 'utf8', timeout: 5000
    }).trim();
    if (status) {
      info.uncommitted = status.split('\n').filter(Boolean).length;
    }
  } catch { /* ignore */ }

  try {
    const log = execSync('git log --oneline -3', {
      cwd: projectRoot, encoding: 'utf8', timeout: 5000
    }).trim();
    if (log) {
      info.recentCommits = log.split('\n');
    }
  } catch { /* ignore */ }

  return info;
}
